### ISSUE TITLE
Remove third-party dependencies (including tracking)

### ISSUE THREAD

**Issue by onion-route** [serai-dex/serai-dex.github.io#2]
Currently serai.exchange loads fonts (fonts.gstatic.com, fonts.googleapis.com) and tracking scripts (googletagmanager.com) from Google.
Although this is convenient, it isn't really compatible with the spirit of decentralization and privacy.

Luckily, the font we use is available under a free license and should therefor not be a problem to directly include in the source code:
https://fonts.google.com/specimen/Playfair+Display/about

I will happily make a merge request.

What are your thoughts on the matter?

**Comment by kayabaNerve** [comment]
I chimed in on Matrix, yet to carry my comments here:

This site was thrown together so we'd technically have a site. No notable amount of thought was put into it so I don't have thoughts on it. What I do have thoughts on is decentralization and privacy, which I love, so I'd love such improvements be made to the site.

The plan is to completely replace the site eventually (not to dismiss improvements to what we have now). We want something comprehensive at explaining Serai while also... actually looking good.

I would love any help you can offer to that end :)

**Comment by onion-route** [comment]
Sounds great, I'll be making the changes to the current site.

**Comment by kayabaNerve** [comment]
Closed by #3.
